---
- name: downloading binaries...
  get_url: >-
    url={{dart_sdk_url}}
    dest=/tmp/{{dart_sdk_zip}}
    mode=0644

- name: create version specific directory
  file: >-
    path={{dart_parent_install_dir}}/{{dart_sdk_name}}
    state=directory
    mode=0755
    
- name: unarchive...
  unarchive: >-
    src=/tmp/{{dart_sdk_zip}}
    dest={{dart_parent_install_dir}}/{{dart_sdk_name}}
    creates={{dart_parent_install_dir}}/{{dart_sdk_name}}/{{dart_sdk_subdir}}

- name: link
  file: >-
    src={{dart_parent_install_dir}}/{{dart_sdk_name}}/{{dart_sdk_subdir}}
    dest={{dart_parent_install_dir}}/{{dart_sdk_subdir}}
    state=link

- name: add to path
  with_items:
    - etc/profile.d/dart.sh
  template: >-
    src={{item}}.j2
    dest=/{{item}}
    mode=0644
    